from .parent import parent_list
from .email import verify_email
from .profileview import student_info,parent_info
from .updateprofile import edit_profile
from .leave import parent_leave_list_create
from .writemsg import write_message
from .viewtimetable import timetable_view
from .viewlunchmenu import lunchmenu_view
from .viewannouncement import announcement_view
from .viewattendance import attendance_view
from .parentimage import update_parent_image