# Generated by Django 5.0.7 on 2024-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
