from .teacher import TeacherSerializer
from .timetable import TimeTableSerializer
from .lunch_menu import LunchMenuSerializer
from .leave import LeaveStatusUpdateSerializer
from .attendance import AttendanceSerializer
from .message import MessageResponseUpdateSerializer
from .announcement import AnnouncementSerializer
from .teacherimage import TeacherImageSerializer
from .teacherprofile import TeacherProfileSerializer
